### ISSUE TITLE
您好，你的博客网址似乎有点问题，能否修正一下呢

### ISSUE THREAD

**Issue by 1922427345** [SukunaShinmyoumaru-hust/Hust-opensource-Xuejie#5]
![Uploading cfa02b21-9534-44af-be38-f8a887dc0ae3.png…]()

**Comment by SukunaShinmyoumaru-hust** [comment]
Hello, my new blog website:sukunahust.moe.I will correct it later.

**Comment by 1922427345** [comment]
Thank you! But I can not find outline of data structure in your blog.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月5日(星期四) 凌晨0:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SukunaShinmyoumaru-hust/Hust-opensource-Xuejie] 您好，你的博客网址似乎有点问题，能否修正一下呢 (Issue #5)














 
Closed #5 as completed.
